### ISSUE TITLE
python script does not work due to "No module named 'requests'"

### ISSUE THREAD

**Issue by Jenicke123** [Tripp-omg/Safety-Checker#3]
The Python script fails because the 'requests' module does not exist. I believe you did not provide the 'requests' file.
![image](https://github.com/user-attachments/assets/f849f911-96e6-4039-a140-ff6834b8447b)
(for clarity this was run in my desktop, I don't know if that has any relevance)

**Comment by Tripp-omg** [comment]
pip install requests

**Comment by Jenicke123** [comment]
Fixed the issue, but ran into a new one.
![image](https://github.com/user-attachments/assets/79574dcd-593b-4426-93f9-ee139a378ba9)
